backend/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include('sewfinal.urls')),
]

sewfinal/models.py
from django.db import models

# Create your models here.

Factory = (
    ('factory1', 'factory1'),
    ('factory2', 'factory2'),
    ('factory3', 'factory3'),
    ('factory4', 'factory4'),
    ('factory5', 'factory5'),
)

Fabric_choices = (
    ('woven', 'Woven'),
    ('knit', 'Knit'),
    ('others', 'Others')
)

Wash = (
    ('non-wash', 'Non-Wash'),
    ('wash', 'Wash'),
)

Style = (
    ('formal', 'Formal'),
    ('casual', 'Casual'),
)


class Category(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    name = models.CharField(max_length=200, null=True)
    category = models.ManyToManyField(Category, blank=True)

    def __str__(self):
        return self.name


class SuperCategory(models.Model):
    name = models.CharField(max_length=200, null=True)
    category = models.ForeignKey(Category, blank=True, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(SubCategory, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class FabricDetails(models.Model):
    pfmno = models.CharField(max_length=100)
    factory = models.CharField(max_length=100, default="0", choices=Factory)
    fabric = models.CharField(max_length=100, default="0", choices=Fabric_choices)
    wash = models.CharField(max_length=100, default="0", choices=Wash)
    category = models.CharField(max_length=200, null=True)
    subcategory = models.CharField(max_length=200, null=True)
    supercategory = models.CharField(max_length=200, null=True)
    styletype = models.CharField(max_length=100, default="0", choices=Style)


class Components(models.Model):
    comp = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.comp


class Attributes(models.Model):
    name = models.CharField(max_length=200, null=True)
    comp = models.ManyToManyField(Components, blank=True)

    def __str__(self):
        return self.name


class StyleDetails(models.Model):
    pfmno = models.ForeignKey(FabricDetails, on_delete=models.CASCADE)
    comp = models.CharField(max_length=200)
    attribute = models.CharField(max_length=200)
    operations = models.CharField(max_length=100)
    complexity = models.IntegerField(default="1")
    spi = models.IntegerField(default="12")
    stitch_length = models.IntegerField(default="3")
    thread_consumption = models.IntegerField()
    machine_auto = models.CharField(max_length=100, default="SNLS")
    work_aid = models.CharField(max_length=100, default="BINDER")
    smv = models.DecimalField(max_digits=6, default="0.33", decimal_places=5)
    allowance = models.DecimalField(max_digits=6, decimal_places=5)
    sam = models.DecimalField(max_digits=6, default="0.53", decimal_places=5)
    ct = models.DecimalField(max_digits=6, default="0.88", decimal_places=5)
    grade = models.CharField(max_length=100)
    comp = models.CharField(max_length=200)
    attribute = models.CharField(max_length=200)


class OrderDetails(models.Model):
    orderno = models.CharField(max_length=100,unique=True)
    styleno = models.CharField(max_length=100,unique=True)
    lineno = models.CharField(max_length=100)
    order_quantity = models.IntegerField()
    mins_shift = models.IntegerField()
    capacity = models.IntegerField()
    expected_skill_level = models.IntegerField()
    target = models.IntegerField()
    fabric = models.CharField(max_length=100, default="0", choices=Fabric_choices,blank=True)
    wash = models.CharField(max_length=100, default="0", choices=Wash,blank=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,blank=True)
    subcategory = models.ForeignKey(SubCategory,on_delete=models.CASCADE,blank=True)
    supercategory = models.ForeignKey(SuperCategory,on_delete=models.CASCADE,blank=True)
    styletype = models.CharField(max_length=100, default="0", choices=Style,blank=True)
    comp = models.ForeignKey(Components,on_delete=models.CASCADE,blank=True)
    attribute = models.ForeignKey(Attributes,on_delete=models.CASCADE,blank=True)

class Obgenerate(models.Model):
    orderno=models.CharField(max_length=190)
    styleno = models.CharField(max_length=100)
    operations = models.CharField(max_length=100)
    complexity = models.IntegerField(default="1")
    spi = models.IntegerField(default="12")
    stitch_length = models.IntegerField(default="3")
    thread_consumption = models.IntegerField()
    machine_auto = models.CharField(max_length=100, default="SNLS")
    work_aid = models.CharField(max_length=100, default="BINDER")
    smv = models.DecimalField(max_digits=6, default="0.33", decimal_places=5)
    allowance = models.DecimalField(max_digits=6, decimal_places=5)
    sam = models.DecimalField(max_digits=6, default="0.53", decimal_places=5)
    ct = models.DecimalField(max_digits=6, default="0.88", decimal_places=5)
    grade = models.CharField(max_length=100)
    mpno = models.IntegerField()
    mpalloc = models.IntegerField()
    Name = models.CharField(max_length=190,blank=True)
    oph = models.IntegerField()
    cost = models.IntegerField()

templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
Official Themes
Take Bootstrap 4 to the next level with official premium themes—toolkits built on Bootstrap with new components and plugins, docs, and build tools.


    <title>PFM</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="hello">JustGetIt</a>
    </nav>
    {% block content %}

    
    
    
    {% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</body>
</html>

templates/obtest.html
{% extends 'base2.html' %}
{% block content %}


<div class="container text-center">
	<h1>obtest</h1>
</div>

<br>
<br>

<div >
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
<button class="btn btn-success" type="submit">submit</button>
</form>

</div>
{% endblock %}

templates/operations.html
{% extends 'base2.html' %}

{% block content %}
{% csrf_token %}

<div class="container text-center">
	<h1>Add Operations</h1>
</div>

<br>
<br>


<form class= "", action="", method="POST", id="myForm">
	<div class="form-group col">

			<div>

				<p><label for="id_pfmno">PFM No.:</label> 
					<select name="pfmno" required="" id="id_pfmno">
							<option value="" selected="">---------</option>

							{% for i in pfmnos %}
							<option value="{{ i.pfmno }}">{{ i.pfmno }}</option>
							{% endfor %}


						</select></p>
				<p>
					<label for="id_styleno">Styleno:</label> <input type="text" name="styleno" value="" maxlength="100" required="" id="id_styleno"></p>
					<p>
						<label for="id_comp">Components :</label> <select name="comp" required="" id="id_comp">


							<option value="1">Common</option>

							<option value="2">Lapels</option>

							<option value="3">Sleeve Cuffs</option>

							<option value="4">Pockets</option>

							<option value="5">Facing</option>

							<option value="6">Misc</option>

						</select></p>
						<p><label for="id_attribute">Attribute:</label> <select name="attribute" required="" id="id_attribute">
							<option value="" selected="">---------</option>

							{% for i in data %}

							{% csrf_token %}
							<option value="{{ i.name }}">{{ i.name }}</option>
							{% endfor %}


						</select></p>
						<p><label for="id_operations">Operations:</label> <input type="text" name="operations" maxlength="100" required="" id="id_operations"></p>
						<p><label for="id_complexity">Complexity:</label> <input type="number" name="complexity" value="1" required="" id="id_complexity"></p>
						<p><label for="id_spi">SPI:</label> <input type="number" name="spi" value="12" required="" id="id_spi"></p>
						<p><label for="id_stitch_length">Stitch length:</label> <input type="number" name="stitch_length" value="3" required="" id="id_stitch_length"></p>
						<p><label for="id_thread_consumption">Thread consumption:</label> <input type="number" name="thread_consumption" required="" id="id_thread_consumption"></p>
						<p><label for="id_machine_auto">Machine auto:</label> <input type="text" name="machine_auto" value="SNLS" maxlength="100" required="" id="id_machine_auto"></p>
						<p><label for="id_work_aid">Work aid:</label> <input type="text" name="work_aid" value="BINDER" maxlength="100" required="" id="id_work_aid"></p>
						<p><label for="id_smv">SMV:</label> <input type="number" name="smv" value="0.33" step="0.00001" required="" id="id_smv"></p>
						<p><label for="id_allowance">Allowance:</label> <input type="number" name="allowance" step="0.00001" required="" id="id_allowance"></p>
						<p><label for="id_sam">SAM:</label> <input type="number" name="sam" value="0.53" step="0.00001" required="" id="id_sam"></p>
						<p><label for="id_ct">CT:</label> <input type="number" name="ct" value="0.88" step="0.00001" required="" id="id_ct"></p>
						<p><label for="id_grade">Grade:</label> <input type="text" name="grade" maxlength="100" required="" id="id_grade"></p>
					</div>


			<br>


			<button class="btn btn-primary" id="id_submit" type="submit" href="/" value="Submit">Submit</button>


			<br>
			<br>


		</form>
	</div>

</body>



 <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	
	<script>
		$("#id_comp").change(function () {
			var comp = $("#id_comp").val();

			$.ajax({
				type: "POST",
				url: "/form2/",
				data: {
					'component': comp,
					'csrfmiddlewaretoken': "{{ csrf_token }}"
				},
				success: function (data) {  
					for(var i=0; i < data["sub"].length; i++){
						$("#id_attribute").append(`<option value="${data['sub'][i]}"> ${data['sub'][i]} </option>`)
					}
	 
				}
			});

		});


	</script> 


	{% endblock %}

templates/orderdetails.html
{% extends 'base2.html' %}

{% block content %}
{% csrf_token %}

<div class="container text-center">
	<h1>Add Order Details</h1>
</div>

<br>
<br>


<form class= "" action="" method="POST" id="myForm">
	<div class="form-group col">
     {% csrf_token %}
		<p><label for="id_orderno">Order No:</label> <input type="text" name="orderno" maxlength="100" required="" id="id_orderno"></p>

		<p><label for="id_stno">Style No:</label> <input type="text" name="stno" maxlength="100" required="" id="id_stno"></p>

		<p><label for="id_lineno">Line No:</label> <input type="text" name="lineno" maxlength="100" required="" id="id_lineno"></p>

		<p><label for="id_order_quantity">Order quantity:</label> <input type="number" name="order_quantity" required="" id="id_order_quantity"></p>

		<p><label for="id_mins_shift">Mins per shift:</label> <input type="number" name="mins_shift" required="" id="id_mins_shift"></p>

		<p><label for="id_capacity">Capacity:</label> <input type="number" name="capacity" required="" id="id_capacity"></p>

		<p><label for="id_expected_skill_level">Expected skill level:</label> <input type="number" name="expected_skill_level" required="" id="id_expected_skill_level"></p>

		<p><label for="id_target">Target:</label> <input type="number" name="target" required="" id="id_target"></p>

		 <p>
        <label for="id_fabric">Fabric: </label>
        <select name="fabric" id="id_fabric">
          <option value="woven">Woven</option>
          <option value="knit">Knit</option>
          <option value="others">Others</option>

        </select>

      </p>

      <p>
        <label for="id_wash">Wash:</label> 
        <select name="wash" id="id_wash">
          <option value="non-wash">Non-Wash</option>
          <option value="wash">Wash</option>
        </select>
      </p>

      <p><label for="id_category">Category:</label> <select name="category" required="" id="id_category">
        <option value="" selected="">---------</option>
        <option value="1">Fabrics</option>
        <option value="2">Home & Living</option>
        <option value="3">Kids</option>
        <option value="4">Mens</option>
        <option value="5">Women</option>
      </select></p>

        <p><label for="id_subcategory">Subcategory:</label> <select name="subcategory" id="id_subcategory">
        <option value="" selected="">---------</option>
        {% for i in data %}
          <option value="{{ i.pk }}">{{ i.name }}</option>
         {% endfor %}


      </select></p>

      <p><label for="id_supercategory">Supercategory:</label> <select name="supercategory"  id="id_supercategory">
        <option value="" selected="">---------</option>

        {% for i in data %}
          <option value="{{ i.pk }}">{{ i.name }}</option>
         {% endfor %}

      </select></p>

      <p><label for="id_styletype">Styletype:</label> <select name="styletype" id="id_styletype">
        <option value="formal">Formal</option>
        <option value="casual">Casual</option>

      </select></p>

     <p>
		<label for="id_comp">Components :</label> <select name="comp" id="id_comp">
		<option value="1">Common</option>
		<option value="2">Lapels</option>
		<option value="3">Sleeve Cuffs</option>
		<option value="4">Pockets</option>
		<option value="5">Facing</option>
		<option value="6">Misc</option>
		</select>
	</p>


	<p><label for="id_attribute">Attribute:</label> <select name="attribute" id="id_attribute">
		<option value="" selected="">---------</option>

		{% for i in data %}

		{% csrf_token %}
		<option value="{{ i.name }}">{{ i.name }}</option>
		{% endfor %}
	</select></p>

	<p>
		
	<input type="checkbox" name="">ABC
	</p>


		<button class="btn btn-primary" id="id_submit" type="submit" href="/" ,="" value="Submit">Submit</button>

	</div>




</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  
  <script>
    $("#id_category").change(function () {
      var cat = $("#id_category").val();

      $.ajax({
        type: "POST",
        url: "/form3/",
        data: {
          'category': cat,
          'csrfmiddlewaretoken': "{{ csrf_token }}"
        },
        success: function (data) {  
          for(var i=0; i < data["sub"].length; i++){
            $("#id_subcategory").append(`<option value="${data['sub'][i]}"> ${data['sub'][i]} </option>`)
          }
   
        }
      });

    });

    $("#id_subcategory").change(function () {
      var subcat = $("#id_subcategory").val();

      $.ajax({
        type: "POST",
        url: "/form3/",
        data: {
          'subcategory': subcat,
          'csrfmiddlewaretoken': "{{ csrf_token }}"
        },
        success: function (data) {  
          for(var i=0; i < data["superc"].length; i++){
            $("#id_supercategory").append(`<option value="${i+1}"> ${data['superc'][i]} </option>`)
          }
            
        }
      });

    });


		$("#id_comp").change(function () {
			var comp = $("#id_comp").val();

			$.ajax({
				type: "POST",
				url: "/form3/",
				data: {
					'component': comp,
					'csrfmiddlewaretoken': "{{ csrf_token }}"
				},
				success: function (data) {  
					for(var i=0; i < data["sub"].length; i++){
						$("#id_attribute").append(`<option value="${data['sub'][i]}"> ${data['sub'][i]} </option>`)
					}
	 
				}
			});

		});

</script>




	{% endblock %}

templates/orderformgen.html
{% extends 'base2.html' %}
{% block content %}


<div class="container text-center">
	<h1>Add Order Details</h1>
</div>

<br>
<br>

<div class="container center">
<form method="post">
{% csrf_token%}
{{form1.as_p}}
{% if not formset %}
<button class="btn btn-primary" id="submit" type="submit">submit</button>
    {% endif %}
</form>
</div>
<div id="ob">
    {% if formset %}
  <form method="post">
  {% csrf_token%}
    {{ formset.management_form }}
  {{ formset.as_table}}
<button class="btn btn-success" type="submit">submit</button>
</form>
    {% endif %}
</div>
<script>
var x="id_form-";
var count=0;
{% for fd in allopp %}
         {% for i in fd %}
             var y = "-orderno";
             var t=x+count+y;
             $("#"+t).val({{ orderno }});
             y= "-styleno";
             t=x+count+y;
             $("#"+t).val({{ styleno}});
             y= "-operations";
             t=x+count+y;
             $("#"+t).val({{ i.operations}});
             y= "-thread_consumption";
             t=x+count+y;
             $("#"+t).val({{ i.thread_consumption}});
             y="-allowance";
             t=x+count+y;
             $("#"+t).val({{ i.allowance}});
             y="-grade";
             t=x+count+y;
             $("#"+t).val({{i.grade}});
             y="-mpno";
             t=x+count+y;
             var no=({{ i.sam }}*{{target}})/ ({{ expskill }}*{{ minps }});
             $("#"+t).val(no);
             count++;
         {% endfor %}

{% endfor %}
</script>
{% endblock %}

templates/responseform.html
{% extends 'base2.html' %}

{% block content %}
{% csrf_token %}

<div class="container text-center">
  <h1>Generate PFM</h1>
</div>

<br>
<br>


<form class= "", action="", method="POST", id="myForm">
  <div class="form-group col">
    {% csrf_token %}

 <p>
        <label for="id_pfmno">PFM No.</label>
        <input type="text"  name="pfmno" id="id_pfmno">
      </p>

      <p>
        <label for="id_factory">Factory: </label>
        <select name="factory" id="id_factory">
          <option value="factory1">Factory1</option>
          <option value="factory1">Factory2</option>
          <option value="factory1">Factory3</option>
          <option value="factory1">Factory4</option>
          <option value="factory1">Factory5</option>
        </select>

      </p>



      <p>
        <label for="id_fabric">Fabric: </label>
        <select name="fabric" id="id_fabric">
          <option value="woven">Woven</option>
          <option value="knit">Knit</option>
          <option value="others">Others</option>

        </select>

      </p>

      <p>
        <label for="id_wash">Wash:</label> 
        <select name="wash" id="id_wash">
          <option value="non-wash">Non-Wash</option>
          <option value="wash">Wash</option>
        </select>
      </p>

      <p><label for="id_category">Category:</label>
          <select name="category" required="" id="id_category">
        <option value="" selected="">---------</option>

        <option value="1">Fabrics</option>

        <option value="2">Home & Living</option>

        <option value="3">Kids</option>

        <option value="4">Mens</option>

        <option value="5">Women</option>

      </select></p>


     

      <p><label for="id_subcategory">Subcategory:</label> <select name="subcategory"  id="id_subcategory">
        <option value="" selected="">---------</option>
        {% for i in data %}
          <option value="{{ i.pk }}">{{ i.name }}</option>
         {% endfor %}


      </select></p>

      <p><label for="id_supercategory">Supercategory:</label> <select name="supercategory"  id="id_supercategory">
        <option value="" selected="">---------</option>

        {% for i in data %}
          <option value="{{ i.pk }}">{{ i.name }}</option>
         {% endfor %}

      </select></p>

      <p><label for="id_styletype">Styletype:</label> <select name="styletype" id="id_styletype">
        <option value="formal">Formal</option>
        <option value="casual">Casual</option>

      </select></p>

      <br>


      <button class="btn btn-primary" id="id_submit" type="submit" href="/", value="Submit">Submit</button>


      <br>
      <br>


    </form>
  </div>

</body>



<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  
  <script>
    $("#id_category").change(function () {
      var cat = $("#id_category").val();

      $.ajax({
        type: "POST",
        url: "/form1/",
        data: {
          'category': cat,
          'csrfmiddlewaretoken': "{{ csrf_token }}"
        },
        success: function (data) {  
          for(var i=0; i < data["sub"].length; i++){
            $("#id_subcategory").append(`<option value="${data['sub'][i]}"> ${data['sub'][i]} </option>`)
          }
   
        }
      });

    });

    $("#id_subcategory").change(function () {
      var subcat = $("#id_subcategory").val();

      $.ajax({
        type: "POST",
        url: "/form1/",
        data: {
          'subcategory': subcat,
          'csrfmiddlewaretoken': "{{ csrf_token }}"
        },
        success: function (data) {  
          for(var i=0; i < data["superc"].length; i++){
            $("#id_supercategory").append(`<option value="${i+1}"> ${data['superc'][i]} </option>`)
          }
            
        }
      });

    });



    $("#id_submit").click(function () {
      var pf = $('#id_pfmno').val();
      var factory = $('#id_factory').find(":selected").text();
      var fabric = $('#id_fabric').find(":selected").text();
      var wash = $('#id_wash').find(":selected").text();
      var category = $('#id_category').find(":selected").text();
      var subcategory = $('#id_subcategory').find(":selected").text();
      var supercategory = $('#id_supercategory').find(":selected").text();

      var stylet = $('#id_styletype').find(":selected").text();

      $.ajax({
        url: '/form1/',
        data: {
          'pf': pf,
          'factory': factory,
          'fabric': fabric,
          'wash':wash,
          'category': category,
          'subcategory': subcategory,
          'supercategory': supercategory,
          'styletype':stylet
        },
        success: function () {
         
            alert("A user with this username already exists.");
          
        }
      });

    });

  </script>





  {% endblock %}